services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:

    App\:
        resource: '../../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migration,Tests,Kernel.php}'