type: FileInterface
type_options:
    use:
        - Enhavo\Bundle\MediaBundle\Model\FileInterface
nullable: true
relation:
    type: ManyToOne
    target_entity: FileInterface::class
    inversed_by: false
form:
    use:
        - Enhavo\Bundle\MediaBundle\Form\Type\MediaType
    class: MediaType
    options:
        translation_domain: "'EnhavoMediaBundle'"
        multiple: 'false'
        upload: 'false'