type: FileInterface
type_options:
    use:
        - Enhavo\Bundle\MediaBundle\Model\FileInterface
nullable: true
relation:
    type: ManyToOne
    target_entity: Enhavo\Bundle\MediaBundle\Model\FileInterface
form:
    use:
        - Enhavo\Bundle\MediaBundle\Form\Type\MediaType
    class: MediaType
    options:
        label: "'Video'"
        help: "'Supported formats are mp4'"
        multiple: 'false'
        upload: 'false'
