enhavo_app:
    mailer:
        defaults:
            from: '%env(resolve:MAILER_FROM)%'
            name: '%env(resolve:MAILER_NAME)%'
            to: '%env(resolve:MAILER_TO)%'
    menu:
        dashboard:
            type: dashboard
        user:
            type: user
        page:
            type: page
        navigation:
            type: navigation
        team_member:
            type: base
            label: Team
            icon: people
            route: app_team_member_index

#        backup:
#            type: backup
