enhavo_app:
    mailer:
        defaults:
            from: '%env(resolve:MAILER_FROM)%'
            name: '%env(resolve:MAILER_NAME)%'
            to: '%env(resolve:MAILER_TO)%'
    menu:
        dashboard:
            type: dashboard
        user:
            type: user
        page:
            type: page
        navigation:
            type: navigation
#        backup:
#            type: backup
