enhavo_media:
  formats:
    block_article_teaser:
      type: image
      width: 640
      height: 360
    block_gallery:
      type: image
      width: 800
      height: 450
    block_header:
      type: image
      width: 1920
      height: 480
    block_header_tablet:
      type: image
      width: 1920
      height: 1080
    block_header_mobile:
      type: image
      width: 960
      height: 1280
    block_text_picture:
      type: image
      width: 960