# @see https://github.com/Sylius/SyliusResourceBundle/blob/master/docs/index.md
sylius_resource:
    resources:
        app.team_member:
            classes:
                model: App\Entity\TeamMember
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                form: App\Form\Type\TeamMemberType
                repository: App\Repository\TeamMemberRepository

