enhavo_search_admin:
    resource: "@EnhavoSearchBundle/Resources/config/routes/admin/*"
    prefix: /admin

enhavo_search_theme_submit:
    path: /search
    controller: App\Controller\SearchController::submitAction

