<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201012205211 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE media_format (id INT AUTO_INCREMENT NOT NULL, file_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(255) DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, parameters JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', lock_at DATETIME DEFAULT NULL, INDEX IDX_62C3E80193CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media_file (id INT AUTO_INCREMENT NOT NULL, mime_type VARCHAR(255) DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, `order` INT DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, parameters LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', token VARCHAR(255) DEFAULT NULL, md5_checksum VARCHAR(255) DEFAULT NULL, library TINYINT(1) DEFAULT NULL, garbage TINYINT(1) NOT NULL, garbage_timestamp DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media_usage (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_node (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, block_id INT DEFAULT NULL, block_class VARCHAR(255) DEFAULT NULL, property VARCHAR(255) DEFAULT NULL, enable TINYINT(1) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, template VARCHAR(255) DEFAULT NULL, INDEX IDX_4311BA3E727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_comment_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, INDEX IDX_4ADEB9E460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_comment (id INT AUTO_INCREMENT NOT NULL, thread_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, user_id INT DEFAULT NULL, comment LONGTEXT DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, published_at DATETIME DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, INDEX IDX_6707307CE2904019 (thread_id), INDEX IDX_6707307C727ACA70 (parent_id), INDEX IDX_6707307CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_thread (id INT AUTO_INCREMENT NOT NULL, enable TINYINT(1) NOT NULL, subject_class VARCHAR(255) DEFAULT NULL, subject_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_template (id INT AUTO_INCREMENT NOT NULL, content_id INT DEFAULT NULL, route_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_C8362FF084A0A3ED (content_id), UNIQUE INDEX UNIQ_C8362FF034ECB4E6 (route_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_resource_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, INDEX IDX_DB1130A460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE taxonomy_taxonomy (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE taxonomy_term (id INT AUTO_INCREMENT NOT NULL, taxonomy_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, position INT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, INDEX IDX_C7ED653A9557E6F6 (taxonomy_id), INDEX IDX_C7ED653A727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_article_list_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, `limit` INT DEFAULT NULL, pagination TINYINT(1) DEFAULT NULL, INDEX IDX_A5944775460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_article_teaser_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, article_id INT DEFAULT NULL, layout SMALLINT DEFAULT NULL, textLeft TINYINT(1) DEFAULT NULL, INDEX IDX_7E6A81C5460D9FD7 (node_id), INDEX IDX_7E6A81C57294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_article (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, picture_id INT DEFAULT NULL, content_id INT DEFAULT NULL, thread_id INT DEFAULT NULL, open_graph_image_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, meta_description LONGTEXT DEFAULT NULL, page_title LONGTEXT DEFAULT NULL, public TINYINT(1) DEFAULT NULL, publication_date DATETIME DEFAULT NULL, published_until DATETIME DEFAULT NULL, priority DOUBLE PRECISION DEFAULT NULL, change_frequency VARCHAR(255) DEFAULT NULL, no_index TINYINT(1) DEFAULT NULL, no_follow TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, open_graph_title LONGTEXT DEFAULT NULL, open_graph_description LONGTEXT DEFAULT NULL, teaser LONGTEXT DEFAULT NULL, INDEX IDX_EFE84AD134ECB4E6 (route_id), UNIQUE INDEX UNIQ_EFE84AD1EE45BDBF (picture_id), UNIQUE INDEX UNIQ_EFE84AD184A0A3ED (content_id), UNIQUE INDEX UNIQ_EFE84AD1E2904019 (thread_id), UNIQUE INDEX UNIQ_EFE84AD136DB1841 (open_graph_image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_article_category (article_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_44F096D97294869C (article_id), INDEX IDX_44F096D912469DE2 (category_id), PRIMARY KEY(article_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_article_tag (article_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_B15FE9E7294869C (article_id), INDEX IDX_B15FE9E12469DE2 (category_id), PRIMARY KEY(article_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_subscribe_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, INDEX IDX_ED2702D7460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_group (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_newsletter (id INT AUTO_INCREMENT NOT NULL, content_id INT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, template VARCHAR(255) DEFAULT NULL, start_at DATETIME DEFAULT NULL, finish_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_9390BC6284A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_newsletter_group (newsletter_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_35E6041022DB1917 (newsletter_id), INDEX IDX_35E60410FE54D947 (group_id), PRIMARY KEY(newsletter_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_newsletter_attachment (newsletter_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_EDFC9CA122DB1917 (newsletter_id), INDEX IDX_EDFC9CA193CB796C (file_id), PRIMARY KEY(newsletter_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_tracking (id INT AUTO_INCREMENT NOT NULL, receiver_id INT DEFAULT NULL, date DATETIME DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, INDEX IDX_757EA476CD53EDB6 (receiver_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_receiver (id INT AUTO_INCREMENT NOT NULL, newsletter_id INT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, sent_at DATETIME DEFAULT NULL, parameters JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', token VARCHAR(255) NOT NULL, INDEX IDX_E0BA4AFC22DB1917 (newsletter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_subscriber (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) DEFAULT NULL, active TINYINT(1) DEFAULT NULL, activated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_subscriber_group (subscriber_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_842BCA037808B1AD (subscriber_id), INDEX IDX_842BCA03FE54D947 (group_id), PRIMARY KEY(subscriber_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_submenu (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, INDEX IDX_E232466B460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_content (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, content_id INT DEFAULT NULL, content_class VARCHAR(255) DEFAULT NULL, INDEX IDX_B8473EDA460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_navigation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_link (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, link VARCHAR(1023) DEFAULT NULL, target VARCHAR(255) DEFAULT NULL, INDEX IDX_12C4C83460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_node (id INT AUTO_INCREMENT NOT NULL, navigation_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, subject_id INT DEFAULT NULL, subject_class VARCHAR(255) DEFAULT NULL, INDEX IDX_B2FF3D3739F79D6D (navigation_id), INDEX IDX_B2FF3D37727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_page (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, content_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, open_graph_image_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, meta_description LONGTEXT DEFAULT NULL, page_title LONGTEXT DEFAULT NULL, public TINYINT(1) DEFAULT NULL, publication_date DATETIME DEFAULT NULL, published_until DATETIME DEFAULT NULL, priority DOUBLE PRECISION DEFAULT NULL, change_frequency VARCHAR(255) DEFAULT NULL, no_index TINYINT(1) DEFAULT NULL, no_follow TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, open_graph_title LONGTEXT DEFAULT NULL, open_graph_description LONGTEXT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, INDEX IDX_93CEAAFA34ECB4E6 (route_id), UNIQUE INDEX UNIQ_93CEAAFA84A0A3ED (content_id), INDEX IDX_93CEAAFA727ACA70 (parent_id), UNIQUE INDEX UNIQ_93CEAAFA36DB1841 (open_graph_image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE routing_route (id INT AUTO_INCREMENT NOT NULL, host VARCHAR(255) DEFAULT NULL, schemes JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', methods JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', defaults JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', requirements JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', options JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', condition_expr VARCHAR(255) DEFAULT NULL, variable_pattern VARCHAR(255) DEFAULT NULL, staticPrefix VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, content_class VARCHAR(255) DEFAULT NULL, content_id INT DEFAULT NULL, INDEX name_idx (name), INDEX prefix_idx (staticPrefix), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redirect_redirect (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, `from` VARCHAR(512) DEFAULT NULL, `to` VARCHAR(512) DEFAULT NULL, code INT DEFAULT NULL, INDEX IDX_87BE679834ECB4E6 (route_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sidebar_sidebar_column_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, column_id INT DEFAULT NULL, sidebar_id INT DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, INDEX IDX_F40A1E75460D9FD7 (node_id), INDEX IDX_F40A1E75BE8E8ED5 (column_id), INDEX IDX_F40A1E753A432888 (sidebar_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sidebar_sidebar (id INT AUTO_INCREMENT NOT NULL, content_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_E383352584A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slider_slide (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, slider_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, url TINYTEXT DEFAULT NULL, public TINYINT(1) DEFAULT NULL, publication_date DATETIME DEFAULT NULL, published_until DATETIME DEFAULT NULL, position INT DEFAULT NULL, UNIQUE INDEX UNIQ_F45BA2063DA5256D (image_id), INDEX IDX_F45BA2062CCC9638 (slider_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slider_slider_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, INDEX IDX_2FB93E94460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slider_slider (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_8F02BF9D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_F7129A8092FC23A8 (username_canonical), UNIQUE INDEX UNIQ_F7129A80A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_F7129A80C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_28657971A76ED395 (user_id), INDEX IDX_28657971FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_gallery_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, INDEX IDX_1E4B24A3460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_gallery_block_file (gallery_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_61E3C6DA4E7AF8F (gallery_id), INDEX IDX_61E3C6DA93CB796C (file_id), PRIMARY KEY(gallery_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_template_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, INDEX IDX_886C4B4A460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_picture_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, file_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, caption VARCHAR(255) DEFAULT NULL, INDEX IDX_7A0C73CE460D9FD7 (node_id), UNIQUE INDEX UNIQ_7A0C73CE93CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_blockquote_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, text LONGTEXT DEFAULT NULL, author VARCHAR(255) DEFAULT NULL, INDEX IDX_F1BBEE4E460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_text_picture_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, file_id INT DEFAULT NULL, text LONGTEXT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, caption VARCHAR(255) DEFAULT NULL, text_left TINYINT(1) DEFAULT NULL, `float` TINYINT(1) DEFAULT NULL, layout INT DEFAULT NULL, INDEX IDX_3B11DE2A460D9FD7 (node_id), UNIQUE INDEX UNIQ_3B11DE2A93CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_video_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, INDEX IDX_D674CB5B460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_text_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, INDEX IDX_B8422614460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_three_column_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, column_one_id INT DEFAULT NULL, column_two_id INT DEFAULT NULL, column_three_id INT DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, INDEX IDX_BEA24F9B460D9FD7 (node_id), INDEX IDX_BEA24F9B5BAD6BDC (column_one_id), INDEX IDX_BEA24F9B30F18C13 (column_two_id), INDEX IDX_BEA24F9B9D7F31B4 (column_three_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_one_column_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, column_id INT DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, INDEX IDX_66A916CD460D9FD7 (node_id), INDEX IDX_66A916CDBE8E8ED5 (column_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_two_column_block (id INT AUTO_INCREMENT NOT NULL, node_id INT DEFAULT NULL, column_one_id INT DEFAULT NULL, column_two_id INT DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, INDEX IDX_3A725155460D9FD7 (node_id), INDEX IDX_3A7251555BAD6BDC (column_one_id), INDEX IDX_3A72515530F18C13 (column_two_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_index (id INT AUTO_INCREMENT NOT NULL, data_set_id INT DEFAULT NULL, word VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) DEFAULT NULL, weight INT DEFAULT NULL, score DOUBLE PRECISION DEFAULT NULL, INDEX IDX_B446A4E870053C01 (data_set_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_total (id INT AUTO_INCREMENT NOT NULL, word VARCHAR(255) NOT NULL, count DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_filter (id INT AUTO_INCREMENT NOT NULL, data_set_id INT DEFAULT NULL, `key` VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, INDEX IDX_A626300270053C01 (data_set_id), INDEX key_idx (`key`), INDEX value_idx (value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_data_set (id INT AUTO_INCREMENT NOT NULL, content_id INT DEFAULT NULL, content_class VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE media_format ADD CONSTRAINT FK_62C3E80193CB796C FOREIGN KEY (file_id) REFERENCES media_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_node ADD CONSTRAINT FK_4311BA3E727ACA70 FOREIGN KEY (parent_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment_comment_block ADD CONSTRAINT FK_4ADEB9E460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment_comment ADD CONSTRAINT FK_6707307CE2904019 FOREIGN KEY (thread_id) REFERENCES comment_thread (id)');
        $this->addSql('ALTER TABLE comment_comment ADD CONSTRAINT FK_6707307C727ACA70 FOREIGN KEY (parent_id) REFERENCES comment_comment (id)');
        $this->addSql('ALTER TABLE comment_comment ADD CONSTRAINT FK_6707307CA76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE template_template ADD CONSTRAINT FK_C8362FF084A0A3ED FOREIGN KEY (content_id) REFERENCES block_node (id)');
        $this->addSql('ALTER TABLE template_template ADD CONSTRAINT FK_C8362FF034ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id)');
        $this->addSql('ALTER TABLE template_resource_block ADD CONSTRAINT FK_DB1130A460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taxonomy_term ADD CONSTRAINT FK_C7ED653A9557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomy_taxonomy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taxonomy_term ADD CONSTRAINT FK_C7ED653A727ACA70 FOREIGN KEY (parent_id) REFERENCES taxonomy_term (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article_list_block ADD CONSTRAINT FK_A5944775460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article_teaser_block ADD CONSTRAINT FK_7E6A81C5460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article_teaser_block ADD CONSTRAINT FK_7E6A81C57294869C FOREIGN KEY (article_id) REFERENCES article_article (id)');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD134ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD1EE45BDBF FOREIGN KEY (picture_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD184A0A3ED FOREIGN KEY (content_id) REFERENCES block_node (id)');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD1E2904019 FOREIGN KEY (thread_id) REFERENCES comment_thread (id)');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD136DB1841 FOREIGN KEY (open_graph_image_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE article_article_category ADD CONSTRAINT FK_44F096D97294869C FOREIGN KEY (article_id) REFERENCES article_article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article_category ADD CONSTRAINT FK_44F096D912469DE2 FOREIGN KEY (category_id) REFERENCES taxonomy_term (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article_tag ADD CONSTRAINT FK_B15FE9E7294869C FOREIGN KEY (article_id) REFERENCES article_article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article_tag ADD CONSTRAINT FK_B15FE9E12469DE2 FOREIGN KEY (category_id) REFERENCES taxonomy_term (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE newsletter_subscribe_block ADD CONSTRAINT FK_ED2702D7460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE newsletter_newsletter ADD CONSTRAINT FK_9390BC6284A0A3ED FOREIGN KEY (content_id) REFERENCES block_node (id)');
        $this->addSql('ALTER TABLE newsletter_newsletter_group ADD CONSTRAINT FK_35E6041022DB1917 FOREIGN KEY (newsletter_id) REFERENCES newsletter_newsletter (id)');
        $this->addSql('ALTER TABLE newsletter_newsletter_group ADD CONSTRAINT FK_35E60410FE54D947 FOREIGN KEY (group_id) REFERENCES newsletter_group (id)');
        $this->addSql('ALTER TABLE newsletter_newsletter_attachment ADD CONSTRAINT FK_EDFC9CA122DB1917 FOREIGN KEY (newsletter_id) REFERENCES newsletter_newsletter (id)');
        $this->addSql('ALTER TABLE newsletter_newsletter_attachment ADD CONSTRAINT FK_EDFC9CA193CB796C FOREIGN KEY (file_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE newsletter_tracking ADD CONSTRAINT FK_757EA476CD53EDB6 FOREIGN KEY (receiver_id) REFERENCES newsletter_receiver (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE newsletter_receiver ADD CONSTRAINT FK_E0BA4AFC22DB1917 FOREIGN KEY (newsletter_id) REFERENCES newsletter_newsletter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE newsletter_subscriber_group ADD CONSTRAINT FK_842BCA037808B1AD FOREIGN KEY (subscriber_id) REFERENCES newsletter_subscriber (id)');
        $this->addSql('ALTER TABLE newsletter_subscriber_group ADD CONSTRAINT FK_842BCA03FE54D947 FOREIGN KEY (group_id) REFERENCES newsletter_group (id)');
        $this->addSql('ALTER TABLE navigation_submenu ADD CONSTRAINT FK_E232466B460D9FD7 FOREIGN KEY (node_id) REFERENCES navigation_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE navigation_content ADD CONSTRAINT FK_B8473EDA460D9FD7 FOREIGN KEY (node_id) REFERENCES navigation_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE navigation_link ADD CONSTRAINT FK_12C4C83460D9FD7 FOREIGN KEY (node_id) REFERENCES navigation_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE navigation_node ADD CONSTRAINT FK_B2FF3D3739F79D6D FOREIGN KEY (navigation_id) REFERENCES navigation_navigation (id)');
        $this->addSql('ALTER TABLE navigation_node ADD CONSTRAINT FK_B2FF3D37727ACA70 FOREIGN KEY (parent_id) REFERENCES navigation_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFA34ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFA84A0A3ED FOREIGN KEY (content_id) REFERENCES block_node (id)');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFA727ACA70 FOREIGN KEY (parent_id) REFERENCES page_page (id)');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFA36DB1841 FOREIGN KEY (open_graph_image_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE redirect_redirect ADD CONSTRAINT FK_87BE679834ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sidebar_sidebar_column_block ADD CONSTRAINT FK_F40A1E75460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sidebar_sidebar_column_block ADD CONSTRAINT FK_F40A1E75BE8E8ED5 FOREIGN KEY (column_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sidebar_sidebar_column_block ADD CONSTRAINT FK_F40A1E753A432888 FOREIGN KEY (sidebar_id) REFERENCES sidebar_sidebar (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sidebar_sidebar ADD CONSTRAINT FK_E383352584A0A3ED FOREIGN KEY (content_id) REFERENCES block_node (id)');
        $this->addSql('ALTER TABLE slider_slide ADD CONSTRAINT FK_F45BA2063DA5256D FOREIGN KEY (image_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE slider_slide ADD CONSTRAINT FK_F45BA2062CCC9638 FOREIGN KEY (slider_id) REFERENCES slider_slider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE slider_slider_block ADD CONSTRAINT FK_2FB93E94460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT FK_28657971A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT FK_28657971FE54D947 FOREIGN KEY (group_id) REFERENCES user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_gallery_block ADD CONSTRAINT FK_1E4B24A3460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_gallery_block_file ADD CONSTRAINT FK_61E3C6DA4E7AF8F FOREIGN KEY (gallery_id) REFERENCES block_gallery_block (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_gallery_block_file ADD CONSTRAINT FK_61E3C6DA93CB796C FOREIGN KEY (file_id) REFERENCES media_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_template_block ADD CONSTRAINT FK_886C4B4A460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_picture_block ADD CONSTRAINT FK_7A0C73CE460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_picture_block ADD CONSTRAINT FK_7A0C73CE93CB796C FOREIGN KEY (file_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE block_blockquote_block ADD CONSTRAINT FK_F1BBEE4E460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_text_picture_block ADD CONSTRAINT FK_3B11DE2A460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_text_picture_block ADD CONSTRAINT FK_3B11DE2A93CB796C FOREIGN KEY (file_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE block_video_block ADD CONSTRAINT FK_D674CB5B460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_text_block ADD CONSTRAINT FK_B8422614460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_three_column_block ADD CONSTRAINT FK_BEA24F9B460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_three_column_block ADD CONSTRAINT FK_BEA24F9B5BAD6BDC FOREIGN KEY (column_one_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_three_column_block ADD CONSTRAINT FK_BEA24F9B30F18C13 FOREIGN KEY (column_two_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_three_column_block ADD CONSTRAINT FK_BEA24F9B9D7F31B4 FOREIGN KEY (column_three_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_one_column_block ADD CONSTRAINT FK_66A916CD460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_one_column_block ADD CONSTRAINT FK_66A916CDBE8E8ED5 FOREIGN KEY (column_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_two_column_block ADD CONSTRAINT FK_3A725155460D9FD7 FOREIGN KEY (node_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_two_column_block ADD CONSTRAINT FK_3A7251555BAD6BDC FOREIGN KEY (column_one_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_two_column_block ADD CONSTRAINT FK_3A72515530F18C13 FOREIGN KEY (column_two_id) REFERENCES block_node (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE search_index ADD CONSTRAINT FK_B446A4E870053C01 FOREIGN KEY (data_set_id) REFERENCES search_data_set (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE search_filter ADD CONSTRAINT FK_A626300270053C01 FOREIGN KEY (data_set_id) REFERENCES search_data_set (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE media_format DROP FOREIGN KEY FK_62C3E80193CB796C');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD1EE45BDBF');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD136DB1841');
        $this->addSql('ALTER TABLE newsletter_newsletter_attachment DROP FOREIGN KEY FK_EDFC9CA193CB796C');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFA36DB1841');
        $this->addSql('ALTER TABLE slider_slide DROP FOREIGN KEY FK_F45BA2063DA5256D');
        $this->addSql('ALTER TABLE block_gallery_block_file DROP FOREIGN KEY FK_61E3C6DA93CB796C');
        $this->addSql('ALTER TABLE block_picture_block DROP FOREIGN KEY FK_7A0C73CE93CB796C');
        $this->addSql('ALTER TABLE block_text_picture_block DROP FOREIGN KEY FK_3B11DE2A93CB796C');
        $this->addSql('ALTER TABLE block_node DROP FOREIGN KEY FK_4311BA3E727ACA70');
        $this->addSql('ALTER TABLE comment_comment_block DROP FOREIGN KEY FK_4ADEB9E460D9FD7');
        $this->addSql('ALTER TABLE template_template DROP FOREIGN KEY FK_C8362FF084A0A3ED');
        $this->addSql('ALTER TABLE template_resource_block DROP FOREIGN KEY FK_DB1130A460D9FD7');
        $this->addSql('ALTER TABLE article_article_list_block DROP FOREIGN KEY FK_A5944775460D9FD7');
        $this->addSql('ALTER TABLE article_article_teaser_block DROP FOREIGN KEY FK_7E6A81C5460D9FD7');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD184A0A3ED');
        $this->addSql('ALTER TABLE newsletter_subscribe_block DROP FOREIGN KEY FK_ED2702D7460D9FD7');
        $this->addSql('ALTER TABLE newsletter_newsletter DROP FOREIGN KEY FK_9390BC6284A0A3ED');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFA84A0A3ED');
        $this->addSql('ALTER TABLE sidebar_sidebar_column_block DROP FOREIGN KEY FK_F40A1E75460D9FD7');
        $this->addSql('ALTER TABLE sidebar_sidebar_column_block DROP FOREIGN KEY FK_F40A1E75BE8E8ED5');
        $this->addSql('ALTER TABLE sidebar_sidebar DROP FOREIGN KEY FK_E383352584A0A3ED');
        $this->addSql('ALTER TABLE slider_slider_block DROP FOREIGN KEY FK_2FB93E94460D9FD7');
        $this->addSql('ALTER TABLE block_gallery_block DROP FOREIGN KEY FK_1E4B24A3460D9FD7');
        $this->addSql('ALTER TABLE block_template_block DROP FOREIGN KEY FK_886C4B4A460D9FD7');
        $this->addSql('ALTER TABLE block_picture_block DROP FOREIGN KEY FK_7A0C73CE460D9FD7');
        $this->addSql('ALTER TABLE block_blockquote_block DROP FOREIGN KEY FK_F1BBEE4E460D9FD7');
        $this->addSql('ALTER TABLE block_text_picture_block DROP FOREIGN KEY FK_3B11DE2A460D9FD7');
        $this->addSql('ALTER TABLE block_video_block DROP FOREIGN KEY FK_D674CB5B460D9FD7');
        $this->addSql('ALTER TABLE block_text_block DROP FOREIGN KEY FK_B8422614460D9FD7');
        $this->addSql('ALTER TABLE block_three_column_block DROP FOREIGN KEY FK_BEA24F9B460D9FD7');
        $this->addSql('ALTER TABLE block_three_column_block DROP FOREIGN KEY FK_BEA24F9B5BAD6BDC');
        $this->addSql('ALTER TABLE block_three_column_block DROP FOREIGN KEY FK_BEA24F9B30F18C13');
        $this->addSql('ALTER TABLE block_three_column_block DROP FOREIGN KEY FK_BEA24F9B9D7F31B4');
        $this->addSql('ALTER TABLE block_one_column_block DROP FOREIGN KEY FK_66A916CD460D9FD7');
        $this->addSql('ALTER TABLE block_one_column_block DROP FOREIGN KEY FK_66A916CDBE8E8ED5');
        $this->addSql('ALTER TABLE block_two_column_block DROP FOREIGN KEY FK_3A725155460D9FD7');
        $this->addSql('ALTER TABLE block_two_column_block DROP FOREIGN KEY FK_3A7251555BAD6BDC');
        $this->addSql('ALTER TABLE block_two_column_block DROP FOREIGN KEY FK_3A72515530F18C13');
        $this->addSql('ALTER TABLE comment_comment DROP FOREIGN KEY FK_6707307C727ACA70');
        $this->addSql('ALTER TABLE comment_comment DROP FOREIGN KEY FK_6707307CE2904019');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD1E2904019');
        $this->addSql('ALTER TABLE taxonomy_term DROP FOREIGN KEY FK_C7ED653A9557E6F6');
        $this->addSql('ALTER TABLE taxonomy_term DROP FOREIGN KEY FK_C7ED653A727ACA70');
        $this->addSql('ALTER TABLE article_article_category DROP FOREIGN KEY FK_44F096D912469DE2');
        $this->addSql('ALTER TABLE article_article_tag DROP FOREIGN KEY FK_B15FE9E12469DE2');
        $this->addSql('ALTER TABLE article_article_teaser_block DROP FOREIGN KEY FK_7E6A81C57294869C');
        $this->addSql('ALTER TABLE article_article_category DROP FOREIGN KEY FK_44F096D97294869C');
        $this->addSql('ALTER TABLE article_article_tag DROP FOREIGN KEY FK_B15FE9E7294869C');
        $this->addSql('ALTER TABLE newsletter_newsletter_group DROP FOREIGN KEY FK_35E60410FE54D947');
        $this->addSql('ALTER TABLE newsletter_subscriber_group DROP FOREIGN KEY FK_842BCA03FE54D947');
        $this->addSql('ALTER TABLE newsletter_newsletter_group DROP FOREIGN KEY FK_35E6041022DB1917');
        $this->addSql('ALTER TABLE newsletter_newsletter_attachment DROP FOREIGN KEY FK_EDFC9CA122DB1917');
        $this->addSql('ALTER TABLE newsletter_receiver DROP FOREIGN KEY FK_E0BA4AFC22DB1917');
        $this->addSql('ALTER TABLE newsletter_tracking DROP FOREIGN KEY FK_757EA476CD53EDB6');
        $this->addSql('ALTER TABLE newsletter_subscriber_group DROP FOREIGN KEY FK_842BCA037808B1AD');
        $this->addSql('ALTER TABLE navigation_node DROP FOREIGN KEY FK_B2FF3D3739F79D6D');
        $this->addSql('ALTER TABLE navigation_submenu DROP FOREIGN KEY FK_E232466B460D9FD7');
        $this->addSql('ALTER TABLE navigation_content DROP FOREIGN KEY FK_B8473EDA460D9FD7');
        $this->addSql('ALTER TABLE navigation_link DROP FOREIGN KEY FK_12C4C83460D9FD7');
        $this->addSql('ALTER TABLE navigation_node DROP FOREIGN KEY FK_B2FF3D37727ACA70');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFA727ACA70');
        $this->addSql('ALTER TABLE template_template DROP FOREIGN KEY FK_C8362FF034ECB4E6');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD134ECB4E6');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFA34ECB4E6');
        $this->addSql('ALTER TABLE redirect_redirect DROP FOREIGN KEY FK_87BE679834ECB4E6');
        $this->addSql('ALTER TABLE sidebar_sidebar_column_block DROP FOREIGN KEY FK_F40A1E753A432888');
        $this->addSql('ALTER TABLE slider_slide DROP FOREIGN KEY FK_F45BA2062CCC9638');
        $this->addSql('ALTER TABLE user_user_group DROP FOREIGN KEY FK_28657971FE54D947');
        $this->addSql('ALTER TABLE comment_comment DROP FOREIGN KEY FK_6707307CA76ED395');
        $this->addSql('ALTER TABLE user_user_group DROP FOREIGN KEY FK_28657971A76ED395');
        $this->addSql('ALTER TABLE block_gallery_block_file DROP FOREIGN KEY FK_61E3C6DA4E7AF8F');
        $this->addSql('ALTER TABLE search_index DROP FOREIGN KEY FK_B446A4E870053C01');
        $this->addSql('ALTER TABLE search_filter DROP FOREIGN KEY FK_A626300270053C01');
        $this->addSql('DROP TABLE media_format');
        $this->addSql('DROP TABLE media_file');
        $this->addSql('DROP TABLE media_usage');
        $this->addSql('DROP TABLE block_node');
        $this->addSql('DROP TABLE comment_comment_block');
        $this->addSql('DROP TABLE comment_comment');
        $this->addSql('DROP TABLE comment_thread');
        $this->addSql('DROP TABLE template_template');
        $this->addSql('DROP TABLE template_resource_block');
        $this->addSql('DROP TABLE taxonomy_taxonomy');
        $this->addSql('DROP TABLE taxonomy_term');
        $this->addSql('DROP TABLE article_article_list_block');
        $this->addSql('DROP TABLE article_article_teaser_block');
        $this->addSql('DROP TABLE article_article');
        $this->addSql('DROP TABLE article_article_category');
        $this->addSql('DROP TABLE article_article_tag');
        $this->addSql('DROP TABLE newsletter_subscribe_block');
        $this->addSql('DROP TABLE newsletter_group');
        $this->addSql('DROP TABLE newsletter_newsletter');
        $this->addSql('DROP TABLE newsletter_newsletter_group');
        $this->addSql('DROP TABLE newsletter_newsletter_attachment');
        $this->addSql('DROP TABLE newsletter_tracking');
        $this->addSql('DROP TABLE newsletter_receiver');
        $this->addSql('DROP TABLE newsletter_subscriber');
        $this->addSql('DROP TABLE newsletter_subscriber_group');
        $this->addSql('DROP TABLE navigation_submenu');
        $this->addSql('DROP TABLE navigation_content');
        $this->addSql('DROP TABLE navigation_navigation');
        $this->addSql('DROP TABLE navigation_link');
        $this->addSql('DROP TABLE navigation_node');
        $this->addSql('DROP TABLE page_page');
        $this->addSql('DROP TABLE routing_route');
        $this->addSql('DROP TABLE redirect_redirect');
        $this->addSql('DROP TABLE sidebar_sidebar_column_block');
        $this->addSql('DROP TABLE sidebar_sidebar');
        $this->addSql('DROP TABLE slider_slide');
        $this->addSql('DROP TABLE slider_slider_block');
        $this->addSql('DROP TABLE slider_slider');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE user_user');
        $this->addSql('DROP TABLE user_user_group');
        $this->addSql('DROP TABLE block_gallery_block');
        $this->addSql('DROP TABLE block_gallery_block_file');
        $this->addSql('DROP TABLE block_template_block');
        $this->addSql('DROP TABLE block_picture_block');
        $this->addSql('DROP TABLE block_blockquote_block');
        $this->addSql('DROP TABLE block_text_picture_block');
        $this->addSql('DROP TABLE block_video_block');
        $this->addSql('DROP TABLE block_text_block');
        $this->addSql('DROP TABLE block_three_column_block');
        $this->addSql('DROP TABLE block_one_column_block');
        $this->addSql('DROP TABLE block_two_column_block');
        $this->addSql('DROP TABLE search_index');
        $this->addSql('DROP TABLE search_total');
        $this->addSql('DROP TABLE search_filter');
        $this->addSql('DROP TABLE search_data_set');
    }
}
