<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle::class => ['all' => true],
    WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::class => ['all' => true],
    Sylius\Bundle\ResourceBundle\SyliusResourceBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\AppBundle\EnhavoAppBundle::class => ['all' => true],
    Enhavo\Bundle\DoctrineExtensionBundle\EnhavoDoctrineExtensionBundle::class => ['all' => true],
    Enhavo\Bundle\MediaBundle\EnhavoMediaBundle::class => ['all' => true],
    Enhavo\Bundle\FormBundle\EnhavoFormBundle::class => ['all' => true],
    Enhavo\Bundle\BlockBundle\EnhavoBlockBundle::class => ['all' => true],
    Enhavo\Bundle\CommentBundle\EnhavoCommentBundle::class => ['all' => true],
    Enhavo\Bundle\TemplateBundle\EnhavoTemplateBundle::class => ['all' => true],
    Enhavo\Bundle\TaxonomyBundle\EnhavoTaxonomyBundle::class => ['all' => true],
    Enhavo\Bundle\ContentBundle\EnhavoContentBundle::class => ['all' => true],
    Enhavo\Bundle\ArticleBundle\EnhavoArticleBundle::class => ['all' => true],
    Enhavo\Bundle\DashboardBundle\EnhavoDashboardBundle::class => ['all' => true],
    Enhavo\Bundle\NewsletterBundle\EnhavoNewsletterBundle::class => ['all' => true],
    Enhavo\Bundle\NavigationBundle\EnhavoNavigationBundle::class => ['all' => true],
    Enhavo\Bundle\PageBundle\EnhavoPageBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\RoutingBundle\EnhavoRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\RedirectBundle\EnhavoRedirectBundle::class => ['all' => true],
    Enhavo\Bundle\SidebarBundle\EnhavoSidebarBundle::class => ['all' => true],
    Enhavo\Bundle\SliderBundle\EnhavoSliderBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Enhavo\Bundle\UserBundle\EnhavoUserBundle::class => ['all' => true],
    Enhavo\Bundle\SearchBundle\EnhavoSearchBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['all' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
];
