# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    Enhavo\Bundle\NavigationBundle\NavItem\NavItemManager:
        public: true
        arguments:
            - '@Enhavo\Component\Type\FactoryInterface[NavItem]'
            - '%enhavo_navigation.nav_items%'
        calls:
            - ['setContainer', ['@service_container']]


    Enhavo\Bundle\UserBundle\User\UserManager:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Enhavo\Bundle\AppBundle\Mailer\MailerManager'
            - '@enhavo_user.repository.user'
            - '@Enhavo\Bundle\UserBundle\Mapper\UserMapper'
            - '@enhavo_app.util.secure_url_token_generator'
            - '@translator'
            - '@form.factory'
            - '@security.encoder_factory.generic'
            - '@router'
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@request_stack'
            - '@security.authentication.session_strategy.main'
            - '@security.user_checker.main'
            - ~
            - '%enhavo_user.config%'
            - '%enhavo_user.mail%'
            - '%enhavo_user.parameters%'
