enhavo_user_user_update:
    options:
        expose: true
    path: /enhavo/user/user/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_user.controller.user:updateAction
        _sylius:
            form:
                options:
                    validation_groups: [ update ]
            viewer:
