App\Entity\Block\HeaderBlock:
    type: entity
    table: app_header_block

    fields:
        headline:
            type: string
            nullable: true
        subheadline:
            type: string
            nullable: true
        cta:
            type: json_array

    manyToOne:
        picture:
            targetEntity: Enhavo\Bundle\MediaBundle\Model\FileInterface
            cascade: [ 'persist', 'refresh', 'remove' ]
            orphanRemoval: true

    lifecycleCallbacks: {  }
