name: Release

on:
    push:
        tags:
            - 'v*.*'

jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: login
              uses: docker/login-action@v1
              with:
                  registry: docker.enhavo.com
                  username: ${{ secrets.DOCKER_ENHAVO_USER }}
                  password: ${{ secrets.DOCKER_ENHAVO_PASSWORD }}
            - name: build and push image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: |
                      docker.enhavo.com/enhavo/demo:latest
