name: Release

on:
    push:
        tags:
            - 'v*.*'

jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: login
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: build and push image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: |
                      enhavo/enhavo-demo:latest
